[project]
name = "DE32-3rd_team5"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Jeonghoon2", email = "ukidd12@naver.com"},
]
dependencies = [
    "torch>=2.4.1",
    "torchvision>=0.19.1",
    "torchaudio>=2.4.1",
    "fastapi[standard]>=0.115.0",
    "uvicorn[standard]>=0.31.0",
    "transformers>=4.45.1",
    "konlpy>=0.6.0",
    "rake-nltk>=1.0.6",
    "nltk>=3.9.1",
    "jigutime>=0.2.1",
    "geopy>=2.4.1",
    "exifread>=3.0.0",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
